# Generated by Django 3.2.2 on 2021-10-01 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=24)),
                ('address_one', models.CharField(max_length=24)),
                ('address_two', models.CharField(blank=True, max_length=24)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('stripe_id', models.CharField(blank=True, max_length=30)),
                ('zip', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=64)),
                ('commercial_account', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('delivery', models.BooleanField()),
                ('delivery_address_one', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_address_two', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_city', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_state', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.product'),
        ),
    ]
