# Generated by Django 3.2.2 on 2021-10-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='invoice_id',
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='PRODUCT', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
