# Generated by Django 3.2.7 on 2022-01-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_product_weight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
